# prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config
bind r source-file ~/.tmux.conf

# switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# enable mouse control
set -g mouse on
set -g mouse-resize-pane on
